import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { SsdlGeneratedModule, SsdlGeneratedSharedModule } from './generated/module.js';
import { SsdlValidator, registerValidationChecks } from './ssdl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SsdlAddedServices = {
    validation: {
        SsdlValidator: SsdlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SsdlServices = LangiumServices & SsdlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SsdlModule: Module<SsdlServices, PartialLangiumServices & SsdlAddedServices> = {
    validation: {
        SsdlValidator: () => new SsdlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSsdlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Ssdl: SsdlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SsdlGeneratedSharedModule
    );
    const Ssdl = inject(
        createDefaultModule({ shared }),
        SsdlGeneratedModule,
        SsdlModule
    );
    shared.ServiceRegistry.register(Ssdl);
    registerValidationChecks(Ssdl);
    return { shared, Ssdl };
}
